name: Profile Sync System

on:
  push:
    branches:
      - main
    paths:
      - "README.md"
      - ".github/workflows/**"
  schedule:
    - cron: "*/4 * * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run generator
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: Jarjarbin06
        run: python scripts/profile_generator.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add generated/
          git commit -m "profile sync update" || exit 0
          git push